global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['172.10.1.20:9090']

  - job_name: 'flaskapp'
    scrape_interval: 15s
    static_configs:
    - targets: ['172.10.1.10:5000']
